# Generated by Django 5.2.9 on 2026-01-04 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_comercio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.comercio', verbose_name='Comercio*'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='id_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='plan',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.plan', verbose_name='Plan*'),
        ),
        migrations.AddField(
            model_name='plancomercio',
            name='id_comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.comercio', verbose_name='Comercio*'),
        ),
        migrations.AddField(
            model_name='plancomercio',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.plan', verbose_name='Plan*'),
        ),
        migrations.AddField(
            model_name='plancomercio',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='id_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.servicio', verbose_name='Servicio*'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.socio', verbose_name='Socio*'),
        ),
        migrations.AddField(
            model_name='solcitudvale',
            name='id_comercio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.comercio', verbose_name='Comercio*'),
        ),
        migrations.AddField(
            model_name='solcitudvale',
            name='id_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.socio', verbose_name='Socio*'),
        ),
        migrations.AddField(
            model_name='solcitudvale',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='id_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.socio', verbose_name='Socio*'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal*'),
        ),
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_tipo_documento_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tipodocumentoidentidad', verbose_name='Tipo Doc. Identidad*'),
        ),
        migrations.AddField(
            model_name='tipoiva',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='socio',
            name='id_tipo_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo de IVA*'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo I.V.A.'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='id_tipo_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo IVA'),
        ),
    ]
