# Generated by Django 5.2.9 on 2026-01-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='cuit',
            field=models.BigIntegerField(unique=True, verbose_name='C.U.I.T.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.BigIntegerField(verbose_name='C.U.I.T.*'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cuit',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='CUIT/CUIL*'),
        ),
        migrations.AlterField(
            model_name='solicitudadhesion',
            name='cuit_solicitud_adhesion',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='CUIT/CUIL*'),
        ),
    ]
