# Generated by Django 6.0 on 2025-12-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='compro_servicio',
            field=models.CharField(default='', max_length=6, verbose_name='Comprobante'),
        ),
    ]
