# Generated by Django 5.2.9 on 2026-03-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.BinaryField(blank=True, max_length='max', null=True, verbose_name='Logo'),
        ),
    ]
