# Generated by Django 6.0 on 2025-12-24 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_servicio_compro_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='interes',
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_plan', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion_plan', models.CharField(max_length=30, verbose_name='Descripción servicio')),
                ('cuota_plan', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Cuotas')),
                ('interes_plan', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)], verbose_name='Interes')),
                ('comision_plan', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)], verbose_name='Comision')),
                ('vigente_desde', models.DateField(blank=True, default=None, null=True, verbose_name='Vigente Desde')),
                ('vencimiento', models.DateField(blank=True, default=None, null=True, verbose_name='Vencimiento')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'plan',
                'ordering': ['descripcion_plan'],
            },
        ),
        migrations.DeleteModel(
            name='Valida',
        ),
    ]
