# Generated by Django 5.2.9 on 2026-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_alter_empresa_logo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='legajo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Legajo'),
        ),
        migrations.AlterField(
            model_name='solicitudadhesion',
            name='legajo_solicitud_adhesion',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Legajo'),
        ),
    ]
