# Generated by Django 5.2.9 on 2026-01-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_alter_comercio_cuit_alter_empresa_cuit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='disponible_credito',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='solicitudadhesion',
            name='limite_credito_solicitud_adhesion',
        ),
    ]
