# Generated by Django 6.0 on 2025-12-24 17:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_remove_empresa_fecha_vencimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='disponible_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Crédito Disponible'),
        ),
        migrations.AddField(
            model_name='socio',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Límite de Crédito'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vencimiento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vigente_desde',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Vigente Desde'),
        ),
        migrations.CreateModel(
            name='PlanComercio',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_plan_comercio', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_plan_comercio', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('id_comercio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.comercio', verbose_name='Comercio*')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.plan', verbose_name='Plan*')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plan Comercio',
                'verbose_name_plural': 'Planes Comercios',
                'db_table': 'plan_comercio',
                'ordering': ['id_plan'],
            },
        ),
    ]
