# Generated by Django 5.2.9 on 2026-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_remove_socio_disponible_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solcitudvale',
            name='consumido_solicitud_vale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Consumido'),
        ),
    ]
