# Generated by Django 6.0 on 2025-12-26 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_socio_disponible_credito_socio_limite_credito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='estatus_socio',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=False, verbose_name='Estatus*'),
        ),
        migrations.CreateModel(
            name='SolicitudAdhesion',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_socio_solicitud_adhesion', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_socio_socio_solicitud_adhesion', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('estado_solicitud_adhesion', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobada'), (3, 'Rechazada')], default=1, verbose_name='Estado Solicitud Adhesión*')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.socio', verbose_name='Socio*')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Adhesión',
                'verbose_name_plural': 'Solicitudes de Adhesión',
                'db_table': 'solicitud_adhesion',
                'ordering': ['id_socio'],
            },
        ),
    ]
