# Generated by Django 5.2.9 on 2026-01-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_solcitudvale_consumido_solicitud_vale'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_vale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.solcitudvale', verbose_name='ID Vale*'),
        ),
    ]
