# Generated by Django 5.2.9 on 2026-01-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_compra_id_vale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_vale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='maestros.solcitudvale', verbose_name='ID Vale*'),
        ),
    ]
