# Generated by Django 6.0 on 2025-12-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_alter_socio_estatus_socio_solicitudadhesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero_documento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número doc.*'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='cuit_solicitud',
            field=models.IntegerField(blank=True, null=True, verbose_name='CUIT/CUIL*'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='email_solicitud',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email*'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='movil_solicitud',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Móvil*'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cuit',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='CUIT/CUIL*'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id_tipo_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo de IVA*'),
        ),
    ]
