# Generated by Django 5.2.9 on 2026-01-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_alter_compra_id_vale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_vale',
            new_name='id_solicitud_vale',
        ),
    ]
