# Generated by Django 6.0 on 2025-12-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_socio_numero_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudadhesion',
            old_name='cuit_solicitud',
            new_name='cuit_solicitud_adhesion',
        ),
        migrations.RenameField(
            model_name='solicitudadhesion',
            old_name='email_solicitud',
            new_name='email_solicitud_adhesion',
        ),
        migrations.RenameField(
            model_name='solicitudadhesion',
            old_name='estatus_socio_socio_solicitud_adhesion',
            new_name='estatus_solicitud_adhesion',
        ),
        migrations.RenameField(
            model_name='solicitudadhesion',
            old_name='id_socio_solicitud_adhesion',
            new_name='id_solicitud_adhesion',
        ),
        migrations.RenameField(
            model_name='solicitudadhesion',
            old_name='movil_solicitud',
            new_name='movil_solicitud_adhesion',
        ),
    ]
