# Generated by Django 5.2.9 on 2026-01-23 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_rename_id_vale_compra_id_solicitud_vale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolcitudVale',
            new_name='SolicitudVale',
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_solicitud_vale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.solicitudvale', verbose_name='ID Vale*'),
        ),
    ]
