# Generated by Django 6.0 on 2025-12-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_rename_cuit_solicitud_solicitudadhesion_cuit_solicitud_adhesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadhesion',
            name='limite_credito_solicitud_adhesion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Límite de Crédito Solicitado'),
        ),
    ]
