# Generated by Django 6.0 on 2025-12-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_solicitudadhesion_limite_credito_solicitud_adhesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolcitudVale',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_solicitud_vale', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_solicitud_vale', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=False, verbose_name='Estatus*')),
                ('monto_solicitud_vale', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Monto Solicitud Vale')),
                ('estado_solicitud_vale', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado'), (4, 'Consumido')], default=1, verbose_name='Estado Solicitud Vale*')),
                ('limite_aprobado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Límite Aprobado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación')),
                ('id_user', models.IntegerField(blank=True, null=True, verbose_name='Usuario*')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('id_comercio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.comercio', verbose_name='Comercio*')),
                ('id_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.socio', verbose_name='Socio*')),
            ],
            options={
                'verbose_name': 'Vale',
                'verbose_name_plural': 'Vales',
                'db_table': 'vale',
                'ordering': ['id_solicitud_vale'],
            },
        ),
    ]
