# Generated by Django 5.2.9 on 2026-02-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_rename_solcitudvale_to_solicitudvale'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='afiliado',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Afiliado*'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='afiliado_solicitud_adhesion',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Afiliado*'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='nombre_solicitud_adhesion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Socio*'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre_localidad',
            field=models.CharField(max_length=40, verbose_name='Nombre Localidad'),
        ),
    ]
