# Generated by Django 5.2.9 on 2026-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_socio_afiliado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='afiliado',
        ),
        migrations.RemoveField(
            model_name='solicitudadhesion',
            name='afiliado_solicitud_adhesion',
        ),
        migrations.AddField(
            model_name='socio',
            name='legajo',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Legajo*'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='legajo_solicitud_adhesion',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Legajo*'),
        ),
    ]
