# Generated by Django 6.0 on 2025-12-29 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_solcitudvale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solcitudvale',
            options={'ordering': ['id_solicitud_vale'], 'verbose_name': 'Solicitud Vale', 'verbose_name_plural': 'Solicitudes de Vales'},
        ),
        migrations.AlterField(
            model_name='solcitudvale',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
