# Generated by Django 5.2.9 on 2026-02-09 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_remove_socio_afiliado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_acceso', to='maestros.socio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Socio',
                'verbose_name_plural': 'Cuentas Socios',
                'db_table': 'cuenta_socio',
            },
        ),
    ]
