# Generated by Django 6.0 on 2026-01-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_alter_solcitudvale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solcitudvale',
            table='solicitud_vale',
        ),
    ]
