# Generated by Django 6.0 on 2026-01-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_alter_solcitudvale_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_vale', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_vale', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=False, verbose_name='Estatus*')),
                ('monto_vale', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Monto Vale*')),
                ('estado_vale', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado'), (4, 'Consumido')], default=1, verbose_name='Estado Vale*')),
                ('fecha_vale', models.DateField(blank=True, null=True, verbose_name='Fecha Compra*')),
                ('id_comercio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.comercio', verbose_name='Comercio*')),
                ('id_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.plan', verbose_name='Plan*')),
                ('id_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.socio', verbose_name='Socio*')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vale',
                'verbose_name_plural': 'Vales',
                'db_table': 'vale',
                'ordering': ['id_vale'],
            },
        ),
    ]
