# Generated by Django 5.2.9 on 2026-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_cuentasocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Idempotency Key'),
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX UX_compra_idempotency_key
            ON compra (idempotency_key)
            WHERE idempotency_key IS NOT NULL;
            """,
            reverse_sql="""
            DROP INDEX UX_compra_idempotency_key ON compra;
            """
        ),
    ]
