# Generated by Django 5.2.9 on 2026-02-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_compra_idempotency_key'),
    ]

    operations = [
        # 1) Drop índice si existe
        migrations.RunSQL(
            """
            IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_compra_idempotency_key' AND object_id = OBJECT_ID('compra'))
                DROP INDEX UX_compra_idempotency_key ON compra;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),

        # 2) Alterar el tipo (esto lo genera Django, dejalo tal cual)
        migrations.AlterField(
            model_name="compra",
            name="idempotency_key",
            field=models.CharField(blank=True, editable=False, max_length=36, null=True, verbose_name="Idempotency Key"),
        ),

        # 3) Re-crear índice filtrado
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX UX_compra_idempotency_key
            ON compra (idempotency_key)
            WHERE idempotency_key IS NOT NULL;
            """,
            reverse_sql="""
            DROP INDEX UX_compra_idempotency_key ON compra;
            """
        ),
    ]
