# Generated by Django 5.2.9 on 2026-02-11 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0014_alter_compra_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='maestros.comercio', verbose_name='Comercio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_comercio', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta Comercio',
                'verbose_name_plural': 'Cuentas Comercio',
                'db_table': 'cuenta_comercio',
            },
        ),
    ]
