# Generated by Django 5.2.9 on 2026-02-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0015_cuentacomercio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudvale',
            options={},
        ),
        migrations.AddField(
            model_name='compra',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador único del dispositivo desde donde se realizó la compra', max_length=255, null=True, verbose_name='ID Dispositivo'),
        ),
        migrations.AddField(
            model_name='compra',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Dispositivo'),
        ),
        migrations.AddField(
            model_name='compra',
            name='device_platform',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Plataforma Dispositivo'),
        ),
        migrations.AddField(
            model_name='socio',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador único del dispositivo del socio', max_length=255, null=True, verbose_name='ID Dispositivo'),
        ),
        migrations.AddField(
            model_name='socio',
            name='device_last_used_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último uso del dispositivo', null=True, verbose_name='Último Uso Dispositivo'),
        ),
        migrations.AddField(
            model_name='socio',
            name='device_model',
            field=models.CharField(blank=True, help_text='Modelo del dispositivo (ej: iPhone 12, Samsung Galaxy S21)', max_length=100, null=True, verbose_name='Modelo Dispositivo'),
        ),
        migrations.AddField(
            model_name='socio',
            name='device_platform',
            field=models.CharField(blank=True, help_text='Sistema operativo (iOS, Android)', max_length=20, null=True, verbose_name='Plataforma Dispositivo'),
        ),
        migrations.AddField(
            model_name='socio',
            name='device_registered_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del primer registro del dispositivo', null=True, verbose_name='Fecha Registro Dispositivo'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador único del dispositivo desde donde se solicitó la adhesión', max_length=255, null=True, verbose_name='ID Dispositivo'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Dispositivo'),
        ),
        migrations.AddField(
            model_name='solicitudadhesion',
            name='device_platform',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Plataforma Dispositivo'),
        ),
        migrations.AddField(
            model_name='solicitudvale',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador único del dispositivo desde donde se solicitó el vale', max_length=255, null=True, verbose_name='ID Dispositivo'),
        ),
        migrations.AddField(
            model_name='solicitudvale',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Dispositivo'),
        ),
        migrations.AddField(
            model_name='solicitudvale',
            name='device_platform',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Plataforma Dispositivo'),
        ),
        migrations.AlterModelTable(
            name='solicitudvale',
            table=None,
        ),
    ]
