# Generated by Django 5.2.9 on 2026-02-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0016_alter_solicitudvale_options_compra_device_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudvale',
            options={'ordering': ['id_solicitud_vale'], 'verbose_name': 'Solicitud Vale', 'verbose_name_plural': 'Solicitudes de Vales'},
        ),
        migrations.AlterModelTable(
            name='solicitudvale',
            table='solicitud_vale',
        ),
    ]
