# Generated by Django 5.2.9 on 2026-03-16 01:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('email_alt', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo alternativo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('iniciales', models.CharField(blank=True, max_length=3, null=True, verbose_name='Iniciales')),
                ('device_id', models.CharField(blank=True, help_text='Identificador único del dispositivo', max_length=255, null=True, verbose_name='ID de Dispositivo')),
                ('device_model', models.CharField(blank=True, help_text='Marca y modelo del dispositivo', max_length=255, null=True, verbose_name='Modelo de Dispositivo')),
                ('device_platform', models.CharField(blank=True, help_text='Sistema operativo (Android, iOS, etc.)', max_length=50, null=True, verbose_name='Plataforma')),
                ('device_registered_at', models.DateTimeField(blank=True, help_text='Fecha de registro inicial del dispositivo', null=True, verbose_name='Fecha Registro Dispositivo')),
                ('device_last_used_at', models.DateTimeField(blank=True, help_text='Última vez que se usó el dispositivo', null=True, verbose_name='Último Uso Dispositivo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRelinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dispositivo Anterior')),
                ('new_device_id', models.CharField(max_length=255, verbose_name='Nuevo Dispositivo')),
                ('device_model', models.CharField(blank=True, default='', max_length=255, verbose_name='Modelo de Dispositivo')),
                ('device_platform', models.CharField(blank=True, default='', max_length=50, verbose_name='Plataforma')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Resolución')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Solicitud')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='Notas Resolución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_relink_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Re-vinculación',
                'verbose_name_plural': 'Solicitudes de Re-vinculación',
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_device_relink_per_user')],
            },
        ),
    ]
