# Generated by Django 5.2.9 on 2026-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identificador único del dispositivo', max_length=255, null=True, verbose_name='ID de Dispositivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_last_used_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se usó el dispositivo', null=True, verbose_name='Último Uso Dispositivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_model',
            field=models.CharField(blank=True, help_text='Marca y modelo del dispositivo', max_length=255, null=True, verbose_name='Modelo de Dispositivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_platform',
            field=models.CharField(blank=True, help_text='Sistema operativo (Android, iOS, etc.)', max_length=50, null=True, verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_registered_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de registro inicial del dispositivo', null=True, verbose_name='Fecha Registro Dispositivo'),
        ),
    ]
